[workspace]
resolver = "3"
members = [
  "iso-tp/can-isotp-queue",
  "embedded-can/embedded-can-embassy-stm32",
  "embedded-can/embedded-can-socketcan",
  "embedded-can/embedded-can-unix-socket",
  "iso-tp/linux-socketcan-iso-tp",
  "thincan",
  "examples/thincan-example",
  "thincan-file-transfer",
]

[workspace.package]
license = "MIT"
repository = "https://github.com/conroy-cheers/thincan"
homepage = "https://github.com/conroy-cheers/thincan"
