on:
  pull_request:
  push:
    branches: [master]

jobs:
  build-pkg:
    name: Check Nix flake
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: DeterminateSystems/determinate-nix-action@v3.16.1
      - run: nix flake check -vL
